apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-chart.name" .}}
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "app-chart.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port}}
    targetPort: {{ .Values.containerport}}
    protocol: TCP
    name: http