name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build Docker image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
       docker build -t hello:${IMAGE_TAG} .

    - name: Run tests
      run: |
       docker run hello:${IMAGE_TAG} pytest
