name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: myapp:${{ github.sha }}

    - name: Build Docker image for testing
      run: |
        docker build -t myapp:test-${{ github.sha }} -f $(pwd)/Dockerfiletest .

    - name: Run tests
      run: |
        docker run -d myapp:test-${{ github.sha }} > container_logs && docker cp $(docker ps -lq):/container_logs .
        cat container_logs
