name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set date and time environment variable
      run: echo ::set-env name=IMAGE_TAG::$(date +'%Y%m%d-%H%M%S')
      
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: hello:${{ env.IMAGE_TAG }}

    - name: Run tests
      run: docker run hello:${{ env.IMAGE_TAG }} pytest
