name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: hello:${{ github.sha }}

    - name: Run tests
      uses: docker://hello:${{ github.sha }}
      with:
        entrypoint: python -m pytest
