name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: hello:${{ vars.GITHUB_SHA }}

    - name: Run tests
      uses: docker://hello:${{ vars.GITHUB_SHA }}
      with:
        entrypoint: python -m pytest
